apiVersion: v1
kind: ConfigMap
metadata:
  name: go-queue-config
  namespace: go-queue
data:
  API_PORT: "8080"
  WORKER_CONCURRENCY: "5"
  REDIS_DB: "0"
  REDIS_QUEUE_KEY: "job_queue"
  DLQ_QUEUE_KEY: "job_queue_dlq"
  RETRY_MAX_ATTEMPTS: "3"
  RETRY_MIN_BACKOFF_MS: "100"
  RETRY_MAX_BACKOFF_MS: "1000"
  LOG_LEVEL: "info"

